### PR TITLE
Fix build, sql and crashes - NPC's and GO's load on purchase

### PR DESCRIPTION
**Pull request by porkserver**
Cleanup and final fix for GO in place

closes https://github.com/azerothcore/mod-guildhouse/issues/22
closes https://github.com/azerothcore/mod-guildhouse/issues/18
closes https://github.com/azerothcore/mod-guildhouse/issues/16
closes https://github.com/azerothcore/mod-guildhouse/issues/11

### CODE REVIEW

**Comment by porkserver** [comment]
HOW TO TEST

1.  Spawn guild housing seller `.npc add 70101`
2. Create Guild `.guild create "Name o Guild" playername` and purchase Guild house
3. Teleport to guild house via npc or by using `.gh tele `command
4. Is starter portal to capital city present?  Yes?  -Joy

Now restart core and log back in
1. Portal still present?
2. Assistant NPC present?  If not use `.gh butler`  - Butler should stay permanent after that

If so... Happy times :)

**Comment by porkserver** [comment]
Working!
With recent core update NPC scripts load immediately.
GO's loading!

Screen Shot 2022-03-30 at 9 02 26 PM

**Review by acidmanifesto — APPROVED** [review]

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
cc @Helias @FrancescoBorzi module not in module team

**Comment by Helias** [comment]
Added the team modules here as Mantainer, thanks for report.

**Review by Helias — APPROVED** [review]

**Comment by porkserver** [comment]
Ah yes, the ChatCommand warnings.  
On my own server I had dismissed these and was going to follow up later.  

Not familiar enough with newer syntax to get the fix right.

**Comment by Helias** [comment]
Check this https://github.com/azerothcore/mod-npc-talent-template/pull/37

**Comment by porkserver** [comment]
In the process of making changes. Getting this error after making chatcommand changes.

```
src/server/game/Chat/ChatCommands/ChatCommand.h:117:51: fatal error: static_assert failed due to requirement 'Acore::dependant_false_v<std::vector<Acore::ChatCommands::ChatCommandBuilder, std::allocator<Acore::ChatCommands::ChatCommandBuilder>>>' "Invalid command handler signature"
    template <typename T> struct HandlerToTuple { static_assert(Acore::dependant_false_v<T>, "Invalid command handler signature"); };
```

**Comment by porkserver** [comment]
Ready for fresh testing

**Comment by Helias** [comment]
if you are 2 that are working on this, I think that your tests are enough.

@SoulSeekkor if you tested this deeply let us know, if so we can merge this PR for me.

Thanks for this big job 🚀

**Comment by Helias** [comment]
I updated the PR description to close automatically all the issues related when this PR will be merged.

image

**Comment by Helias** [comment]
image

Put the npcflag without the flag 1 if by default the NPCs have not a gossip menu assigned.

(@Kitzunu this caused a lot of startup errors for the modules, I checked that in multiple modules is a standard strategy to put npcflag = 1, but in practice would be a real issue if the NPC has npcflag=1 without having a gossip menu or used for it I think.)

**Comment by porkserver** [comment]
I'm new to some of this, If the NPC's have scripts, doesn't the flag need to be on?

**Comment by porkserver** [comment]
Yes, with NPCFlag = 1 off the scripts stop working and NPC is not longer reactive.

**Comment by Helias** [comment]
? Are you sure? try to put it npcflag=0, it should work if your C++ enable the gossip

**Comment by porkserver** [comment]
Deleted cache, flag set to 0.
No reaction from NPC's at all
Screen Shot 2022-04-03 at 10 03 42 AM
Screen Shot 2022-04-03 at 10 03 32 AM

**Comment by SoulSeekkor** [comment]
All of my tests seemed to be good, only thing was I had the gossip menu warnings but wasn't sure on clearing those.  One thing I wanted to double-check with the new CommandTable structure was the Console yes or no, does that refer to the command being allowed via the telnet console?

**Comment by porkserver** [comment]
That's correct to my knowledge.

The discussion in the discord was to call the npcflag via the mod internally bypassing the error and also removing the need to even reference the custom NPC in the worldserver file.

Not a terribly bad issue but blocking merge because those are "Sniffable fields by Cucks" :P

**Comment by porkserver** [comment]
I was combing through the talent-template npc mod and gambler mod per @Helias suggestion, which recently changed to npcflags=0

**Comment by porkserver** [comment]
The following setflag was mentioned and I have been looking at some examples if you have any thought @SoulSeekkor 
It would be called at the beginning of the creature scripts...

            me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);

**Comment by Helias** [comment]
ok done https://github.com/porkserver/mod_guildhouse/pull/3

this is what I did, and I made a PR to your branch

**Comment by SoulSeekkor** [comment]
> ```
>         me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
> ```

@porkserver So I believe they just updated the core to have a new unit helper for setting flags on units, so it'll probably need to get changed to that (I suspect there may be a deprecation warning during compile?).  Not a big deal I can take a look at that tomorrow, I need to probably change the Console::Yes to No as well.

**Comment by porkserver** [comment]
@Helias helped solve the issue.  PR was updates and is passing :)
Pending merge :0

**Comment by Helias** [comment]
Merged!

**Pull request merged**
