### PR TITLE
add spirit healer fix build warnings

### PR DESCRIPTION
**Pull request by milestorme**
added spirit healer fix build warnings merge updates

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
I dunno if it's okay to merge this but squash it when merging :D "squash and merge"

**Comment by milestorme** [comment]
@BarbzYHOOL I don’t have permission  to merge on this repo , tested on my server though , sorry about messy pull , super busy I can delete and do a cleaner pull if you like

**Comment by BarbzYHOOL** [comment]
no it's okay, we can squash it

hmm ok so the team doesn't have permission to this module

**Comment by milestorme** [comment]
Yeah same with cfbg module too

**Pull request merged**
