### PR TITLE
fix for last PR ACE remove

### PR DESCRIPTION
**Pull request by Mitradis**
https://github.com/azerothcore/azerothcore-wotlk/pull/4608

### CODE REVIEW

**Comment by Mitradis** [comment]
Hmmm on windows i success build it

**Comment by FrancescoBorzi** [comment]
still failing :(

**Comment by FrancescoBorzi** [comment]
cc @Winfidonarleyan

**Comment by Winfidonarleyan** [comment]
I haven't changed the database yet.
All check passed - https://github.com/azerothcore/azerothcore-wotlk/actions/runs/607832286
Problem in module and developers, who don't know how to do modules right

**Pull request closed without merging**
